# create_fft256_ip.tcl — Preliminary Tcl helper to generate the Xilinx FFT256 IP.
#
# STATUS: PRELIMINARY / NOT VERIFIED IN VIVADO
# Property names and values are based on Xilinx xfft v9.1 documentation and
# known IP Catalog conventions for Vivado 2022.2.
# Do NOT run this script in production without reviewing all TODO items.
# All CONFIG.* property names must be verified with report_property (see
# scripts/probe_fft256_ip_properties.tcl).
#
# Purpose:
#   Create a Xilinx FFT IP (xfft v9.1) configured for a 256-point forward FFT
#   suitable for PSS/SSS processing in the Meyr integer CFO estimator path.
#   Interface: AXI4-Stream.
#   Output order: natural order (bin 0 = DC, no fftshift).
#
# Intended use:
#   1. Open Vivado 2022.2 (Windows or Linux with license).
#   2. Optionally open or create a project (IP can also be created standalone).
#   3. Source this script:
#        source scripts/create_fft256_ip.tcl
#   4. Review generated reports under reports/.
#   5. Inspect ip/fft256_xilinx/ for generated XCI and instantiation template.
#   6. Instantiate fft256_xilinx in rtl/fft256_xilinx_wrapper.v replacing the
#      USE_BEHAVIORAL_STUB=0 TODO block (future Step 37+).
#
# FFT configuration targets (verify via probe_fft256_ip_properties.tcl):
#   Transform length : 256
#   Transform type   : Forward FFT
#   Input data width : 16 bits (I and Q separate, packed as {Q[15:0], I[15:0]})
#   Output ordering  : Natural order (k=0 DC, k=1..127 positive, k=128..255 negative)
#   Scaling          : Scaled (conservative, avoids overflow with typical signals)
#   Interface        : AXI4-Stream
#   Config channel   : FWD_INV driven; scale schedule driven via s_axis_config_tdata
#   TLAST input      : asserted on sample 255 (final sample of each 256-point frame)
#   TLAST output     : expected on bin 255
#
# See docs/step36A_fft256_xilinx_ip_audit.md for full configuration rationale.

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
set ip_name       "fft256_xilinx"
set output_dir    "./ip/fft256_xilinx"
set report_dir    "./reports"

# ---------------------------------------------------------------------------
# Create output directories
# ---------------------------------------------------------------------------
file mkdir $output_dir
file mkdir $report_dir

# ---------------------------------------------------------------------------
# Create Xilinx FFT IP (xfft v9.1)
# TODO: Confirm the correct version string for your Vivado installation:
#       vivado -mode tcl -nolog -nojournal -c "get_ipdefs -filter {NAME =~ xfft*}"
# ---------------------------------------------------------------------------
puts "INFO: Creating xfft IP: $ip_name"

create_ip \
    -name xfft \
    -vendor xilinx.com \
    -library ip \
    -version 9.1 \
    -module_name $ip_name \
    -dir $output_dir

# ---------------------------------------------------------------------------
# Probe and report all available properties BEFORE configuring.
# This lets you verify exact CONFIG.* key names for your Vivado version.
# ---------------------------------------------------------------------------
set prop_file [open "${report_dir}/fft256_ip_properties_raw.txt" w]
puts $prop_file "# All properties for $ip_name before configuration"
puts $prop_file "# Generated by create_fft256_ip.tcl"
puts $prop_file ""
foreach prop [list_property [get_ips $ip_name]] {
    set val [get_property $prop [get_ips $ip_name]]
    puts $prop_file [format "%-60s %s" $prop $val]
}
close $prop_file
puts "INFO: Raw property dump written to ${report_dir}/fft256_ip_properties_raw.txt"

# ---------------------------------------------------------------------------
# Configure the IP
#
# TODO: Verify every CONFIG.* key against the raw property dump above.
#       The names below are based on xfft v9.1 documentation and are preliminary.
#       Common mismatches between Vivado versions:
#         CONFIG.FFT_Length vs CONFIG.Transform_Length
#         CONFIG.Input_Data_Width vs CONFIG.Data_Width
#         CONFIG.Phase_Factor_Width vs CONFIG.Coefficient_Width
#         CONFIG.Output_Ordering vs CONFIG.Output_Ordering_Option
#         CONFIG.Scaling_Options vs CONFIG.Scaling_Option
# ---------------------------------------------------------------------------
set_property -dict [list \
    CONFIG.transform_length          {256}                          \
    CONFIG.implementation_options    {pipelined_streaming_io}      \
    CONFIG.data_format               {fixed_point}                 \
    CONFIG.input_width               {16}                          \
    CONFIG.phase_factor_width        {16}                          \
    CONFIG.output_ordering           {natural_order}               \
    CONFIG.throttle_scheme           {realtime}                    \
    CONFIG.rounding_modes            {convergent_rounding}         \
    CONFIG.scaling_options           {scaled}                      \
    CONFIG.aclken                    {false}                       \
    CONFIG.ovflo                     {false}                       \
    CONFIG.xk_index                  {true}                        \
] [get_ips $ip_name]

# TODO: If any set_property call fails with "invalid property name", consult
#       reports/fft256_ip_properties_raw.txt for correct names.
#       Then update this script and re-run.

# ---------------------------------------------------------------------------
# Report configured properties
# ---------------------------------------------------------------------------
set cfg_file [open "${report_dir}/fft256_ip_config_summary.txt" w]
puts $cfg_file "# Configured properties for $ip_name"
puts $cfg_file "# Generated by create_fft256_ip.tcl"
puts $cfg_file ""
puts $cfg_file [format "%-60s %s" "Property" "Value"]
puts $cfg_file [string repeat "-" 80]
foreach prop [list_property [get_ips $ip_name]] {
    if {[string match "CONFIG.*" $prop]} {
        set val [get_property $prop [get_ips $ip_name]]
        puts $cfg_file [format "%-60s %s" $prop $val]
    }
}
close $cfg_file
puts "INFO: Configured property summary written to ${report_dir}/fft256_ip_config_summary.txt"

# ---------------------------------------------------------------------------
# Generate all IP output products
# This creates .xci, synthesis stubs, simulation models, example design, etc.
# ---------------------------------------------------------------------------
puts "INFO: Generating IP output products for $ip_name ..."
generate_target all [get_ips $ip_name]

# ---------------------------------------------------------------------------
# Export instantiation template if available
# ---------------------------------------------------------------------------
set templ_file "${output_dir}/${ip_name}_inst.v"
if {[catch {
    export_ip_user_files \
        -of_objects [get_ips $ip_name] \
        -no_script \
        -reset_run \
        -force
} err]} {
    puts "WARNING: export_ip_user_files failed: $err"
    puts "INFO: Instantiation template may still exist in ${output_dir}/${ip_name}/"
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
puts ""
puts "========================================================"
puts "  FFT256 Xilinx IP creation script complete"
puts "========================================================"
puts "  IP name    : $ip_name"
puts "  Output dir : $output_dir"
puts "  Reports    : $report_dir"
puts ""
puts "NEXT STEPS:"
puts "  1. Review reports/fft256_ip_properties_raw.txt"
puts "       Verify CONFIG.* property names match the keys used above."
puts "       If any key was wrong, correct this script and re-run."
puts ""
puts "  2. Review reports/fft256_ip_config_summary.txt"
puts "       Confirm transform_length=256, input_width=16, output_ordering=natural_order"
puts "       Confirm phase_factor_width, rounding_modes, scaling_options."
puts ""
puts "  3. Check the generated XCI in ip/fft256_xilinx/"
puts "       Look for: fft256_xilinx.xci"
puts ""
puts "  4. Find the instantiation template (look for *_inst.v or *_inst.vhd)"
puts "       Verify port names:"
puts "         s_axis_config_tdata  s_axis_config_tvalid  s_axis_config_tready"
puts "         s_axis_data_tdata    s_axis_data_tvalid    s_axis_data_tready"
puts "         s_axis_data_tlast"
puts "         m_axis_data_tdata    m_axis_data_tvalid    m_axis_data_tready"
puts "         m_axis_data_tlast    m_axis_data_tuser"
puts "         m_axis_status_tdata  m_axis_status_tvalid"
puts "         event_frame_started  event_tlast_unexpected  event_tlast_missing"
puts "         event_data_in_channel_halt  event_data_out_channel_halt"
puts "         event_status_channel_halt"
puts ""
puts "  5. Verify m_axis_data_tdata packing:"
puts "       For 16-bit input/output: {Im[15:0], Re[15:0]} in bits [31:0]"
puts "       Confirm with: check outputs from a single-tone test vector."
puts ""
puts "  6. Verify config channel format:"
puts "       s_axis_config_tdata[0] = FWD_INV (1=forward, 0=inverse)"
puts "       s_axis_config_tdata[8:1] = SCALE_SCH (scaling schedule)"
puts "       (bit positions may vary — verify from XCI/docs)"
puts ""
puts "  7. Note pipeline latency from the XCI or documentation."
puts "       Typical pipelined 256-point FFT: ~100-400 clocks from first input"
puts "       to first output (depends on implementation option)."
puts ""
puts "  8. Update rtl/fft256_xilinx_wrapper.v USE_BEHAVIORAL_STUB=0 block"
puts "       with actual $ip_name instantiation (Step 37+)."
puts "========================================================"
