#!/usr/bin/env python3
"""
generate_meyr_term2_rom.py  —  Meyr term2 ROM generator template

PURPOSE
-------
Given external mU and goldU complex sequences (the transmitted PSS/SSS
time-domain waveforms), compute:

    term2[j] = mU[j + CP_LEN] * conj(goldU[j + CP_LEN])
             = (mU_i + j*mU_q) * (goldU_i - j*goldU_q)
             real: mU_i*goldU_i + mU_q*goldU_q
             imag: mU_q*goldU_i - mU_i*goldU_q

and emit the result as a Verilog $readmemh ROM initialisation file suitable
for loading into meyr_term2_ref_rom.v.

STATUS
------
Real mU/goldU sequences are NOT available in this repository.
They are defined in pluto.h and generated by the transmitter application,
which is external to this codebase.  See docs/step33_real_mU_goldU_term2_reference_audit.md.

This script is a *template*.  It will function correctly once real mU/goldU
data is provided via --input-json or --input-csv.

USAGE
-----
    python3 generate_meyr_term2_rom.py --help
    python3 generate_meyr_term2_rom.py --input-json data/mu_goldu.json --output rtl/term2_rom_init.mem
    python3 generate_meyr_term2_rom.py --input-csv  data/mu_goldu.csv  --output rtl/term2_rom_init.mem
    python3 generate_meyr_term2_rom.py --test-synthetic --output rtl/term2_rom_synthetic.mem

INPUT JSON FORMAT
-----------------
{
  "cp_len": 32,
  "nsc":    256,
  "mu_i":    [<float>, ...],   // length >= nsc + cp_len
  "mu_q":    [<float>, ...],
  "goldu_i": [<float>, ...],
  "goldu_q": [<float>, ...]
}

INPUT CSV FORMAT
----------------
Header row: mu_i, mu_q, goldu_i, goldu_q
Rows 0..nsc+cp_len-1 (indices 0 to nsc+cp_len-1).
CP_LEN is supplied via --cp-len (default 32); NSC via --nsc (default 256).

OUTPUT FORMAT ($readmemh)
-------------------------
One line per ROM entry (NSC lines total), each line:
    <64-hex-digits>   →  {term2_q[31:0], term2_i[31:0]}
Values are two's-complement signed 32-bit integers.
The upper/lower halves match the packed format expected by meyr_term2_ref_rom.v.
"""

import argparse
import json
import math
import struct
import sys


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def to_signed32(x: int) -> int:
    x = int(x) & 0xFFFF_FFFF
    if x >= (1 << 31):
        x -= (1 << 32)
    return x


def pack_iq(i32: int, q32: int) -> str:
    """Return 16-hex-char string packing {q[31:0], i[31:0]}."""
    i_u = int(i32) & 0xFFFF_FFFF
    q_u = int(q32) & 0xFFFF_FFFF
    return f"{q_u:08x}{i_u:08x}"


def compute_term2(mu_i, mu_q, goldu_i, goldu_q, cp_len: int, nsc: int):
    """
    Compute term2[j] for j in 0..nsc-1.
    Reads mu/goldu at index (j + cp_len).
    Returns list of (t2_i_float, t2_q_float).
    """
    results = []
    for j in range(nsc):
        k = j + cp_len
        ai, aq = mu_i[k], mu_q[k]
        bi, bq = goldu_i[k], goldu_q[k]
        # (ai + j*aq) * (bi - j*bq)
        t2_i = ai * bi + aq * bq
        t2_q = aq * bi - ai * bq
        results.append((t2_i, t2_q))
    return results


def scale_and_quantise(samples, scale: float, width: int = 32):
    """
    Multiply each float sample by scale and round to nearest integer,
    clamped to signed-width range.
    Returns list of (int_i, int_q).
    """
    limit = (1 << (width - 1)) - 1
    out = []
    for (fi, fq) in samples:
        si = max(-limit - 1, min(limit, round(fi * scale)))
        sq = max(-limit - 1, min(limit, round(fq * scale)))
        out.append((si, sq))
    return out


# ---------------------------------------------------------------------------
# synthetic fallback  (XOR-shift32 identical to meyr_integer_cfo_core.v)
# ---------------------------------------------------------------------------
SYNTHETIC_SEED = 0xCAFEB0BB


def xorshift32(state: int) -> int:
    state ^= (state << 13) & 0xFFFF_FFFF
    state ^= (state >> 17) & 0xFFFF_FFFF
    state ^= (state << 5)  & 0xFFFF_FFFF
    return state & 0xFFFF_FFFF


def generate_synthetic_term2(nsc: int):
    """Reproduce the identical PRNG ROM used inside meyr_integer_cfo_core.v."""
    state = SYNTHETIC_SEED
    entries = []
    for _ in range(nsc):
        state = xorshift32(state)
        raw_i = state
        state = xorshift32(state)
        raw_q = state
        # Match the Verilog: signed 8-bit slice of lower byte
        t2_i = raw_i & 0xFF
        if t2_i >= 128:
            t2_i -= 256
        t2_q = raw_q & 0xFF
        if t2_q >= 128:
            t2_q -= 256
        entries.append((t2_i, t2_q))
    return entries


# ---------------------------------------------------------------------------
# loaders
# ---------------------------------------------------------------------------

def load_json(path: str):
    with open(path) as f:
        d = json.load(f)
    cp_len = int(d["cp_len"])
    nsc    = int(d["nsc"])
    mu_i    = [float(x) for x in d["mu_i"]]
    mu_q    = [float(x) for x in d["mu_q"]]
    goldu_i = [float(x) for x in d["goldu_i"]]
    goldu_q = [float(x) for x in d["goldu_q"]]
    required = nsc + cp_len
    for name, seq in [("mu_i", mu_i), ("mu_q", mu_q),
                      ("goldu_i", goldu_i), ("goldu_q", goldu_q)]:
        if len(seq) < required:
            sys.exit(f"ERROR: '{name}' has {len(seq)} entries, need >= {required} (nsc+cp_len)")
    return cp_len, nsc, mu_i, mu_q, goldu_i, goldu_q


def load_csv(path: str, cp_len: int, nsc: int):
    import csv
    mu_i, mu_q, goldu_i, goldu_q = [], [], [], []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            mu_i.append(float(row["mu_i"]))
            mu_q.append(float(row["mu_q"]))
            goldu_i.append(float(row["goldu_i"]))
            goldu_q.append(float(row["goldu_q"]))
    required = nsc + cp_len
    for name, seq in [("mu_i", mu_i), ("mu_q", mu_q),
                      ("goldu_i", goldu_i), ("goldu_q", goldu_q)]:
        if len(seq) < required:
            sys.exit(f"ERROR: '{name}' has {len(seq)} entries, need >= {required} (nsc+cp_len)")
    return mu_i, mu_q, goldu_i, goldu_q


# ---------------------------------------------------------------------------
# writer
# ---------------------------------------------------------------------------

def write_mem(path: str, entries):
    """Write NSC lines of 16-hex-char {q,i} pairs to a $readmemh file."""
    with open(path, "w") as f:
        f.write("// Meyr term2 ROM  —  generated by generate_meyr_term2_rom.py\n")
        f.write("// Format: {term2_q[31:0], term2_i[31:0]} (two's-complement)\n")
        for (i_val, q_val) in entries:
            f.write(pack_iq(i_val, q_val) + "\n")
    print(f"[OK] Wrote {len(entries)} entries to '{path}'")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Compute Meyr term2 ROM from mU/goldU sequences.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    src = parser.add_mutually_exclusive_group()
    src.add_argument("--input-json", metavar="FILE",
                     help="JSON file with cp_len, nsc, mu_i, mu_q, goldu_i, goldu_q")
    src.add_argument("--input-csv",  metavar="FILE",
                     help="CSV file with header: mu_i,mu_q,goldu_i,goldu_q")
    src.add_argument("--test-synthetic", action="store_true",
                     help="Generate ROM using the same XOR-shift32 PRNG as meyr_integer_cfo_core.v "
                          "(for self-test only — not real mU/goldU data)")

    parser.add_argument("--output", metavar="FILE", default="term2_rom_init.mem",
                        help="Output $readmemh file (default: term2_rom_init.mem)")
    parser.add_argument("--cp-len", type=int, default=32,
                        help="Cyclic prefix length (default: 32; used with --input-csv)")
    parser.add_argument("--nsc",    type=int, default=256,
                        help="Number of subcarriers (default: 256; used with --input-csv and --test-synthetic)")
    parser.add_argument("--scale",  type=float, default=1.0,
                        help="Multiply float samples by SCALE before quantising (default: 1.0)")

    args = parser.parse_args()

    if args.test_synthetic:
        print(f"[INFO] Generating synthetic PRNG ROM (NSC={args.nsc}, seed=0x{SYNTHETIC_SEED:08X})")
        print("[WARN] This is NOT real mU/goldU data.  For self-test / CI only.")
        entries = generate_synthetic_term2(args.nsc)

    elif args.input_json:
        print(f"[INFO] Loading from JSON: {args.input_json}")
        cp_len, nsc, mu_i, mu_q, goldu_i, goldu_q = load_json(args.input_json)
        samples = compute_term2(mu_i, mu_q, goldu_i, goldu_q, cp_len, nsc)
        entries = scale_and_quantise(samples, args.scale)
        print(f"[INFO] cp_len={cp_len}, nsc={nsc}, scale={args.scale}")

    elif args.input_csv:
        print(f"[INFO] Loading from CSV: {args.input_csv}")
        mu_i, mu_q, goldu_i, goldu_q = load_csv(args.input_csv, args.cp_len, args.nsc)
        samples = compute_term2(mu_i, mu_q, goldu_i, goldu_q, args.cp_len, args.nsc)
        entries = scale_and_quantise(samples, args.scale)
        print(f"[INFO] cp_len={args.cp_len}, nsc={args.nsc}, scale={args.scale}")

    else:
        parser.print_help()
        print("\n[STATUS] Real mU/goldU data is NOT available in this repository.")
        print("         Provide --input-json or --input-csv once the transmitter sequences")
        print("         have been extracted.  Use --test-synthetic for self-test only.")
        sys.exit(0)

    write_mem(args.output, entries)


if __name__ == "__main__":
    main()
