# probe_dds_ip_properties.tcl — Probe Xilinx DDS Compiler IP properties in Vivado.
#
# STATUS: OPTIONAL — created to evaluate DDS Compiler as an alternative to
#         CORDIC rotate mode for NCO sin/cos generation.
#         Run this AFTER probe_cordic_ip_properties.tcl to compare options.
#
# PURPOSE:
#   Create a temporary DDS Compiler IP instance and dump all available properties
#   to help decide whether DDS Compiler is preferable to CORDIC rotate mode for
#   replacing nco_phase_gen_xilinx_wrapper.v.
#
# TARGET: Vivado 2022.2
#   DDS Compiler IP identifier: xilinx.com:ip:dds_compiler:6.0
#
# Usage (Vivado Tcl console, with any project open):
#   source scripts/probe_dds_ip_properties.tcl
#
# Outputs:
#   reports/dds_ip_properties.txt   — full property dump
#   reports/dds_ip_analysis.txt     — compatibility analysis vs existing NCO design
#
# ---------------------------------------------------------------------------
# Key DDS Compiler considerations vs existing nco_phase_gen design:
#
# 1. PHASE ACCUMULATOR OWNERSHIP
#    DDS Compiler can own the phase accumulator internally (Dithered mode, etc.)
#    OR accept an external phase increment (No_Phase_Accumulator mode).
#    The existing design has the accumulator in RTL (nco_phase_gen_xilinx_wrapper.v).
#    If DDS owns the accumulator, phase_reset semantics must be re-implemented
#    using the DDS phase_clear or reload port.  This complicates integration.
#    CORDIC rotate mode is simpler for this project because it takes an explicit
#    phase input and does NOT own the accumulator.
#
# 2. PHASE RESOLUTION
#    DDS Compiler typically supports higher phase resolution than CORDIC (e.g., 48-bit
#    internal accumulator).  However, the existing design only needs 16-32 bits.
#
# 3. OUTPUT FORMAT
#    DDS Compiler output is typically packed AXI-Stream, similar to CORDIC.
#    Sine/cosine channel ordering must be verified.
#
# 4. LATENCY
#    DDS Compiler latency is typically configurable.  Check CONFIG.Latency.
#
# 5. AREA vs ACCURACY
#    For a single NCO channel on ZCU102, area savings from DDS vs CORDIC are minor.
#    CORDIC rotate mode is the recommended choice for this project because:
#      a) It does not own the phase accumulator.
#      b) It is a more direct drop-in for the existing nco_phase_gen interface.
#      c) The CORDIC IP is already being used for atan2; familiarity reduces risk.
#    DDS is still documented here for completeness.

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------
set report_dir  "./reports"
set scratch_dir "./build/dds_probe_scratch"

file mkdir $report_dir
file mkdir $scratch_dir

set dds_inst_name  "dds_nco_probe"

puts "INFO: Creating DDS Compiler probe instance: $dds_inst_name"

# ---------------------------------------------------------------------------
# Create DDS instance
# ---------------------------------------------------------------------------
if {[catch {
    create_ip \
        -name dds_compiler \
        -vendor xilinx.com \
        -library ip \
        -version 6.0 \
        -module_name $dds_inst_name \
        -dir $scratch_dir
} err]} {
    set msg "ERROR: create_ip failed for DDS Compiler: $err"
    puts $msg
    set fh [open "$report_dir/dds_ip_properties.txt" w]
    puts $fh $msg
    puts $fh "Possible causes:"
    puts $fh "  - DDS Compiler not in catalog (check IP Catalog)"
    puts $fh "  - Wrong version: try dds_compiler:6.0 or check 'search_catalog -name dds_compiler'"
    puts $fh "  - No active project; run with an open project or in batch mode"
    close $fh
    puts "Report written to $report_dir/dds_ip_properties.txt"
    return
}

# ---------------------------------------------------------------------------
# Dump full property report
# ---------------------------------------------------------------------------
set prop_file "$report_dir/dds_ip_properties.txt"
set fh [open $prop_file w]
puts $fh "# DDS Compiler IP Property Probe"
puts $fh "# Generated by scripts/probe_dds_ip_properties.tcl"
puts $fh "# Vivado version: [version -short]"
puts $fh "# Timestamp: [clock format [clock seconds]]"
puts $fh "#"
puts $fh "# Purpose: compare DDS Compiler vs CORDIC rotate mode for NCO replacement."
puts $fh ""
puts $fh "# All properties:"
puts $fh [report_property [get_ips $dds_inst_name] -return_string]
puts $fh ""
puts $fh "# CONFIG.* values (default configuration):"
foreach prop [lsort [list_property [get_ips $dds_inst_name]]] {
    if {[string match "CONFIG.*" $prop]} {
        puts $fh "  [format %-50s $prop] = [get_property $prop [get_ips $dds_inst_name]]"
    }
}
close $fh
puts "INFO: DDS property report: $prop_file"

# ---------------------------------------------------------------------------
# Write compatibility analysis
# ---------------------------------------------------------------------------
set analysis_file "$report_dir/dds_ip_analysis.txt"
set fa [open $analysis_file w]
puts $fa "# DDS Compiler vs CORDIC Rotate Mode — Compatibility Analysis"
puts $fa "# Generated by scripts/probe_dds_ip_properties.tcl"
puts $fa "# Timestamp: [clock format [clock seconds]]"
puts $fa ""
puts $fa "# Existing design: nco_phase_gen_xilinx_wrapper.v"
puts $fa "#   - External 32-bit phase accumulator (in RTL)"
puts $fa "#   - phase_reset port clears accumulator and blocks valid"
puts $fa "#   - load_step / step_word ports for NCO frequency control"
puts $fa "#   - AXI-Stream-like output: sin_out[15:0], cos_out[15:0], sincos_valid"
puts $fa ""
puts $fa "# KEY QUESTION: Does DDS own the phase accumulator?"
puts $fa "# Check CONFIG.Parameter_Selection or similar in dds_ip_properties.txt."
puts $fa "# If DDS_Compiler owns the accumulator:"
puts $fa "#   - phase_reset must be mapped to DDS phase_clear or equivalent port."
puts $fa "#   - step_word must be mapped to DDS phase_increment reload port."
puts $fa "#   - This is a significant interface change from the existing wrapper."
puts $fa "#   - CORDIC rotate mode is preferred in this case."
puts $fa ""
puts $fa "# KEY QUESTION: What is the DDS output packing?"
puts $fa "# Expected: TDATA = {sin_channel, cos_channel} but channel ordering varies."
puts $fa "# Check generated stub or CONFIG.Output_Selection."
puts $fa ""
puts $fa "# KEY QUESTION: What latency does DDS produce?"
puts $fa "# Target: 15 cycles (to match existing wrapper LATENCY=15)."
puts $fa "# Check CONFIG.Latency after configuration."
puts $fa ""
puts $fa "# RECOMMENDATION (based on design analysis):"
puts $fa "#   CORDIC rotate mode is preferred for this project because:"
puts $fa "#   1. It does NOT own the phase accumulator."
puts $fa "#   2. It accepts an explicit phase input — maps directly to existing interface."
puts $fa "#   3. The atan2 path already uses CORDIC; reusing the same IP family reduces risk."
puts $fa "#   4. DDS integration would require restructuring phase_reset/step_word semantics."
puts $fa "#"
puts $fa "#   DDS Compiler may be revisited for a future high-precision NCO upgrade"
puts $fa "#   if CORDIC phase resolution proves insufficient."
close $fa
puts "INFO: DDS analysis: $analysis_file"

# ---------------------------------------------------------------------------
# Clean up scratch instance
# ---------------------------------------------------------------------------
if {[catch {remove_ip [get_ips $dds_inst_name]} err]} {
    puts "WARN: Could not remove DDS probe instance: $err"
}

puts ""
puts "============================================================"
puts "DDS Compiler probe complete."
puts "Reports:"
puts "  $prop_file"
puts "  $analysis_file"
puts "============================================================"
puts "Review dds_ip_analysis.txt for recommendation on DDS vs CORDIC."
