# probe_fft256_ip_properties.tcl — Probe all Xilinx xfft IP properties and
# dump them to reports/ for manual audit.
#
# STATUS: READY TO RUN IN WINDOWS VIVADO
# This script does not commit to any configuration.
# It only creates the IP, dumps all properties, then removes the temporary IP.
# Safe to run as the first step before create_fft256_ip.tcl.
#
# Purpose:
#   Discover exact CONFIG.* property names and their legal values for the
#   Xilinx xfft IP in the target Vivado version (default: 2022.2).
#   This resolves uncertainty about property names before running
#   create_fft256_ip.tcl which applies the desired configuration.
#
# Intended use:
#   1. Open Vivado 2022.2 (Windows or Linux with license).
#   2. Source this script:
#        source scripts/probe_fft256_ip_properties.tcl
#   3. Inspect generated reports:
#        reports/fft256_ip_properties.txt       — all property names and values
#        reports/fft256_ip_config_summary.txt   — CONFIG.* properties only
#   4. Provide the reports to the RTL_SYNC project (commit or paste into chat).
#   5. Proceed to create_fft256_ip.tcl with verified property names.
#
# See docs/step36A_fft256_xilinx_ip_audit.md for the full audit procedure.

set probe_name  "fft256_probe_tmp"
set report_dir  "./reports"
set output_dir  "./ip/_probe_tmp"

file mkdir $report_dir
file mkdir $output_dir

# ---------------------------------------------------------------------------
# Step 1: Discover available xfft IP versions in the IP Catalog
# ---------------------------------------------------------------------------
puts "INFO: Searching IP catalog for xfft..."
set fft_ipdefs [get_ipdefs -filter {NAME =~ xfft*} -quiet]
if {[llength $fft_ipdefs] == 0} {
    puts "WARNING: No xfft IP definitions found in IP catalog."
    puts "         Ensure you have a Vivado project open with IP Catalog access."
    puts "         Try: create_project -in_memory -part xck26-sfvc784-2LV-c (or your part)"
} else {
    puts "INFO: Found xfft IP definitions:"
    foreach ipdef $fft_ipdefs {
        puts "        $ipdef"
    }
}

set version_file [open "${report_dir}/fft256_ip_versions.txt" w]
puts $version_file "# Available xfft IP versions in Vivado IP Catalog"
puts $version_file "# Generated by probe_fft256_ip_properties.tcl"
puts $version_file ""
foreach ipdef $fft_ipdefs {
    puts $version_file $ipdef
}
close $version_file
puts "INFO: Version list written to ${report_dir}/fft256_ip_versions.txt"

# ---------------------------------------------------------------------------
# Step 2: Create a temporary FFT IP instance (no configuration applied)
# ---------------------------------------------------------------------------
puts "INFO: Creating temporary probe IP: $probe_name"

# TODO: If version 9.1 is not available, change to match your Vivado version.
#       Check reports/fft256_ip_versions.txt for the correct version string.
if {[catch {
    create_ip \
        -name xfft \
        -vendor xilinx.com \
        -library ip \
        -version 9.1 \
        -module_name $probe_name \
        -dir $output_dir
} err]} {
    puts "ERROR: create_ip failed: $err"
    puts "       Check version string. Available versions are in reports/fft256_ip_versions.txt"
    return
}

# ---------------------------------------------------------------------------
# Step 3: Dump ALL properties to reports/fft256_ip_properties.txt
# ---------------------------------------------------------------------------
puts "INFO: Dumping all properties for $probe_name ..."
set prop_file [open "${report_dir}/fft256_ip_properties.txt" w]

puts $prop_file "# All properties for Xilinx xfft IP (probe)"
puts $prop_file "# IP instance: $probe_name"
puts $prop_file "# Generated by probe_fft256_ip_properties.tcl"
puts $prop_file "# Date: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $prop_file ""
puts $prop_file [format "%-70s %s" "Property" "Default Value"]
puts $prop_file [string repeat "-" 100]

foreach prop [list_property [get_ips $probe_name]] {
    if {[catch {
        set val [get_property $prop [get_ips $probe_name]]
        puts $prop_file [format "%-70s %s" $prop $val]
    } perr]} {
        puts $prop_file [format "%-70s %s" $prop "(error reading: $perr)"]
    }
}
close $prop_file
puts "INFO: All properties written to ${report_dir}/fft256_ip_properties.txt"

# ---------------------------------------------------------------------------
# Step 4: Dump CONFIG.* properties only for quick audit
# ---------------------------------------------------------------------------
set cfg_file [open "${report_dir}/fft256_ip_config_summary.txt" w]
puts $cfg_file "# CONFIG.* properties for Xilinx xfft IP (probe defaults)"
puts $cfg_file "# Use these names in create_fft256_ip.tcl set_property -dict block"
puts $cfg_file "# Generated by probe_fft256_ip_properties.tcl"
puts $cfg_file ""
puts $cfg_file [format "%-60s %s" "CONFIG Property" "Default Value"]
puts $cfg_file [string repeat "-" 90]

foreach prop [list_property [get_ips $probe_name]] {
    if {[string match "CONFIG.*" $prop]} {
        if {[catch {
            set val [get_property $prop [get_ips $probe_name]]
            puts $cfg_file [format "%-60s %s" $prop $val]
        } perr]} {
            puts $cfg_file [format "%-60s %s" $prop "(error: $perr)"]
        }
    }
}
close $cfg_file
puts "INFO: CONFIG summary written to ${report_dir}/fft256_ip_config_summary.txt"

# ---------------------------------------------------------------------------
# Step 5: Check for specific properties we expect to need
# ---------------------------------------------------------------------------
set target_props {
    CONFIG.transform_length
    CONFIG.Transform_Length
    CONFIG.implementation_options
    CONFIG.Implementation_Options
    CONFIG.data_format
    CONFIG.Data_Format
    CONFIG.input_width
    CONFIG.Input_Data_Width
    CONFIG.Input_Width
    CONFIG.phase_factor_width
    CONFIG.Phase_Factor_Width
    CONFIG.output_ordering
    CONFIG.Output_Ordering
    CONFIG.throttle_scheme
    CONFIG.Throttle_Scheme
    CONFIG.rounding_modes
    CONFIG.Rounding_Modes
    CONFIG.scaling_options
    CONFIG.Scaling_Options
    CONFIG.aclken
    CONFIG.Has_ACLKEN
    CONFIG.ovflo
    CONFIG.xk_index
}

set audit_file [open "${report_dir}/fft256_ip_property_audit.txt" w]
puts $audit_file "# Property existence audit for fft256_xilinx configuration"
puts $audit_file "# Shows which target property names exist in this Vivado version"
puts $audit_file ""
puts $audit_file [format "%-50s %-10s %s" "Target Property" "Exists?" "Current Value"]
puts $audit_file [string repeat "-" 90]

foreach tprop $target_props {
    set exists "NO"
    set val    "N/A"
    if {[lsearch -exact [list_property [get_ips $probe_name]] $tprop] >= 0} {
        set exists "YES"
        catch { set val [get_property $tprop [get_ips $probe_name]] }
    }
    puts $audit_file [format "%-50s %-10s %s" $tprop $exists $val]
}
close $audit_file
puts "INFO: Property audit written to ${report_dir}/fft256_ip_property_audit.txt"

# ---------------------------------------------------------------------------
# Step 6: Clean up temporary probe IP
# ---------------------------------------------------------------------------
puts "INFO: Removing temporary probe IP $probe_name ..."
if {[catch {
    remove_files -quiet [get_files -of_objects [get_ips $probe_name] -quiet]
    delete_ip_run [get_ips $probe_name] -quiet
} clerr]} {
    puts "INFO: Could not auto-remove probe IP (non-fatal): $clerr"
    puts "INFO: You may need to manually remove ip/_probe_tmp from your project."
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
puts ""
puts "========================================================"
puts "  FFT256 IP property probe complete"
puts "========================================================"
puts ""
puts "  Files generated:"
puts "    reports/fft256_ip_versions.txt        — available xfft versions"
puts "    reports/fft256_ip_properties.txt      — all properties (full dump)"
puts "    reports/fft256_ip_config_summary.txt  — CONFIG.* only (quick reference)"
puts "    reports/fft256_ip_property_audit.txt  — existence check for target props"
puts ""
puts "  NEXT STEPS:"
puts "    1. Examine reports/fft256_ip_property_audit.txt"
puts "         Identify which CONFIG.* names exist in this Vivado version."
puts "    2. Update scripts/create_fft256_ip.tcl set_property -dict block"
puts "         Replace any 'NO' entries with the correct name from the full dump."
puts "    3. Run: source scripts/create_fft256_ip.tcl"
puts "    4. Commit reports/ and ip/fft256_xilinx/*.xci to git."
puts "========================================================"
