# probe_cordic_ip_properties.tcl — Probe Xilinx CORDIC IP properties in Vivado.
#
# PURPOSE:
#   Create temporary CORDIC IP instances and dump all available properties to
#   report files so that correct CONFIG.* key names and value enumerations can
#   be confirmed before writing production create_cordic_*.tcl scripts.
#
# STATUS: READY FOR WINDOWS VIVADO — requires an open or batch Vivado project.
#
# Usage (Vivado Tcl console, with any project open):
#   source scripts/probe_cordic_ip_properties.tcl
#
# Usage (Vivado batch, no project needed — creates a temporary in-memory project):
#   vivado -mode batch -source scripts/probe_cordic_ip_properties.tcl
#
# Outputs:
#   reports/cordic_atan2_property_probe.txt  — properties for vectoring/atan2 mode
#   reports/cordic_rotate_property_probe.txt — properties for rotate/sincos mode
#   reports/cordic_ip_properties.txt         — combined summary
#
# Notes:
#   - Temporary IP instances are created in a scratch directory and deleted after probing.
#   - This script does NOT generate output products or modify any real IP directory.
#   - Property names and value enumerations are Vivado-version-dependent.
#     Running this probe in Vivado 2022.2 will give the authoritative names.
#   - Xilinx CORDIC IP identifier: xilinx.com:ip:cordic:6.0
#     (may vary; check IP Catalog if create_ip fails)

# ---------------------------------------------------------------------------
# Setup — report directory
# ---------------------------------------------------------------------------
set report_dir  "./reports"
set scratch_dir "./build/cordic_probe_scratch"

file mkdir $report_dir
file mkdir $scratch_dir

# ---------------------------------------------------------------------------
# Helper: create a CORDIC IP instance, dump properties, delete it
# ---------------------------------------------------------------------------
proc probe_cordic_instance {inst_name config_dict report_file} {
    global scratch_dir

    puts "INFO: Creating CORDIC probe instance: $inst_name"

    # Create the IP in the scratch directory
    if {[catch {
        create_ip \
            -name cordic \
            -vendor xilinx.com \
            -library ip \
            -version 6.0 \
            -module_name $inst_name \
            -dir $scratch_dir
    } err]} {
        set msg "ERROR: create_ip failed for $inst_name: $err"
        puts $msg
        set fh [open $report_file w]
        puts $fh $msg
        puts $fh "Possible causes:"
        puts $fh "  - CORDIC IP not in catalog (check IP Catalog)"
        puts $fh "  - Wrong version: try cordic:6.0 or check 'search_catalog -name cordic'"
        puts $fh "  - No active project: run in batch mode or open a project first"
        close $fh
        return
    }

    # Apply requested configuration overrides
    if {[llength $config_dict] > 0} {
        if {[catch {
            set_property -dict $config_dict [get_ips $inst_name]
        } err]} {
            puts "WARN: set_property failed for $inst_name: $err"
            puts "WARN: Properties will be dumped from default configuration."
        }
    }

    # Open file and write full property dump
    set fh [open $report_file w]
    puts $fh "# CORDIC IP Property Probe: $inst_name"
    puts $fh "# Generated by scripts/probe_cordic_ip_properties.tcl"
    puts $fh "# Vivado version: [version -short]"
    puts $fh "# Timestamp: [clock format [clock seconds]]"
    puts $fh "# Config requested: $config_dict"
    puts $fh "#"
    puts $fh "# Column format from report_property:"
    puts $fh "#   Property | Type | Read-only | Visible | Value"
    puts $fh "# ============================================================"
    puts $fh ""

    # Dump all properties
    set prop_lines [report_property [get_ips $inst_name] -return_string]
    puts $fh $prop_lines

    puts $fh ""
    puts $fh "# ============================================================"
    puts $fh "# CONFIG.* properties only (direct set_property targets):"
    puts $fh "# ============================================================"
    foreach prop [list_property [get_ips $inst_name]] {
        if {[string match "CONFIG.*" $prop]} {
            set val [get_property $prop [get_ips $inst_name]]
            puts $fh "  $prop = $val"
        }
    }

    puts $fh ""
    puts $fh "# ============================================================"
    puts $fh "# AXI-Stream port list (from get_bd_intf_pins or get_pins):"
    puts $fh "# ============================================================"
    # Try to enumerate ports from the IP definition
    if {[catch {
        foreach port [get_property PORT_NAMES [get_ips $inst_name]] {
            puts $fh "  PORT: $port"
        }
    } err]} {
        puts $fh "  (PORT_NAMES not available via this method)"
        puts $fh "  Run generate_target all \[get_ips $inst_name\] then inspect the stub."
    }

    close $fh
    puts "INFO: Report written to $report_file"

    # Delete the scratch instance
    if {[catch {remove_ip [get_ips $inst_name]} err]} {
        puts "WARN: Could not remove scratch IP $inst_name: $err"
        puts "WARN: Delete manually from $scratch_dir"
    }
}

# ---------------------------------------------------------------------------
# Probe 1 — CORDIC Vectoring (atan2) mode
# ---------------------------------------------------------------------------
# Functional_Selection = Translate corresponds to vectoring/atan2 in Xilinx docs.
# The exact enum value may be:
#   "Translate"     (Xilinx CORDIC v6.0 GUI label for vectoring)
#   "Arc_Tan"       (older naming in some versions)
#   "Translate"     (confirmed in Vivado 2019.x and 2022.x via report_property)
# After running this probe, check the VALUE_RANGE line for CONFIG.Functional_Selection
# to see all valid enum options for your installed version.

set atan2_config [list \
    CONFIG.Functional_Selection    {Translate} \
    CONFIG.Architectural_Configuration {Fully_Pipelined} \
    CONFIG.Pipelining_Mode         {Maximum} \
    CONFIG.Input_Width             {32} \
    CONFIG.Output_Width            {16} \
]

probe_cordic_instance \
    "cordic_atan2_probe" \
    $atan2_config \
    "$report_dir/cordic_atan2_property_probe.txt"

# ---------------------------------------------------------------------------
# Probe 2 — CORDIC Rotate mode (sin/cos generation)
# ---------------------------------------------------------------------------
# Functional_Selection = Rotate gives cos/sin from phase input.
# Phase input port: s_axis_phase_tdata (signed, Q1.15 or Scaled Radians)
# Output port:      m_axis_dout_tdata  (packed {sin[15:0], cos[15:0]})
# Scale_Compensation = true removes the CORDIC gain factor (~1.6468).

set rotate_config [list \
    CONFIG.Functional_Selection    {Rotate} \
    CONFIG.Architectural_Configuration {Fully_Pipelined} \
    CONFIG.Pipelining_Mode         {Maximum} \
    CONFIG.Input_Width             {16} \
    CONFIG.Output_Width            {16} \
    CONFIG.Phase_Format            {Scaled_Radians} \
]

probe_cordic_instance \
    "cordic_rotate_probe" \
    $rotate_config \
    "$report_dir/cordic_rotate_property_probe.txt"

# ---------------------------------------------------------------------------
# Write combined summary
# ---------------------------------------------------------------------------
set summary_file "$report_dir/cordic_ip_properties.txt"
set fh [open $summary_file w]
puts $fh "# CORDIC IP Property Probe — Combined Summary"
puts $fh "# Generated by scripts/probe_cordic_ip_properties.tcl"
puts $fh "# Vivado version: [version -short]"
puts $fh "# Timestamp: [clock format [clock seconds]]"
puts $fh "#"
puts $fh "# This file summarises what was probed."
puts $fh "# See individual report files for full property dumps:"
puts $fh "#   reports/cordic_atan2_property_probe.txt"
puts $fh "#   reports/cordic_rotate_property_probe.txt"
puts $fh "#"
puts $fh "# KEY QUESTIONS TO ANSWER FROM THE PROPERTY REPORTS:"
puts $fh "#"
puts $fh "# 1. What is the exact enum for CONFIG.Functional_Selection?"
puts $fh "#    Expected: {Translate} for atan2/vectoring, {Rotate} for sin/cos"
puts $fh "#    Confirm from: VALUE_RANGE line in cordic_atan2_property_probe.txt"
puts $fh "#"
puts $fh "# 2. What is the CONFIG key for pipeline depth / latency?"
puts $fh "#    Expected candidates: CONFIG.Pipelining_Mode, CONFIG.Num_Iterations"
puts $fh "#    Target latency: 15 cycles (match existing cordic_atan2.v LATENCY=15)"
puts $fh "#"
puts $fh "# 3. What is the output phase format for atan2 mode?"
puts $fh "#    Expected: Scaled_Radians — output range maps to [-pi, +pi] as"
puts $fh "#    signed integer over output width.  pi -> +2^(OUTPUT_WIDTH-1) - 1."
puts $fh "#    This means with OUTPUT_WIDTH=16: pi -> +32767 (matches project convention)."
puts $fh "#    Confirm: CONFIG.Phase_Format and its VALUE_RANGE."
puts $fh "#"
puts $fh "# 4. What does s_axis_cartesian_tdata pack for atan2 input?"
puts $fh "#    Expected: lower half = X (I), upper half = Y (Q)"
puts $fh "#    Matches: rtl/cordic_atan2_xilinx_wrapper.v convention."
puts $fh "#"
puts $fh "# 5. Is aresetn available?  Is aclken available?"
puts $fh "#    Expected: CONFIG.Has_ARESETn = true, CONFIG.Has_ACLKEN = false (for now)"
puts $fh "#"
puts $fh "# 6. What does m_axis_dout_tdata pack for rotate output?"
puts $fh "#    Expected: {Y[15:0], X[15:0]} = {sin[15:0], cos[15:0]}"
puts $fh "#    Confirm from the generated stub .vhd or .v port list."
puts $fh "#"
puts $fh "# 7. Does Scale_Compensation exist and what is its effect?"
puts $fh "#    Expected: removes CORDIC gain, normalises output to [-1, +1] range."
puts $fh "#"
puts $fh "# 8. What is the minimum/maximum supported Input_Width and Output_Width?"
puts $fh "#    Relevant for confirming 32-bit Cartesian input and 16-bit phase output."
puts $fh "#"
puts $fh "# NEXT STEPS after reviewing these reports:"
puts $fh "#   1. Update scripts/create_cordic_atan2_ip.tcl with confirmed property names."
puts $fh "#   2. Update scripts/create_cordic_sincos_ip.tcl with confirmed property names."
puts $fh "#   3. Run both create scripts to generate actual XCI files."
puts $fh "#   4. Verify latency by reading CONFIG.Latency or from IP report."
puts $fh "#   5. Proceed to simulation integration in a future step."
close $fh

puts ""
puts "============================================================"
puts "CORDIC property probe complete."
puts "Reports written:"
puts "  $report_dir/cordic_atan2_property_probe.txt"
puts "  $report_dir/cordic_rotate_property_probe.txt"
puts "  $report_dir/cordic_ip_properties.txt"
puts "============================================================"
puts "Review the CONFIG.* sections and VALUE_RANGE lines in each"
puts "report before running create_cordic_atan2_ip.tcl or"
puts "create_cordic_sincos_ip.tcl."
